
---
title: "Our World In Data: Life Expectancy"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(mongolite)
library(janitor)
library(DBI)
library(odbc)
```
## Connect to SQL SERVER
```{r}
## https://db.rstudio.com/databases/microsoft-sql-server/
db1 <- DBI::dbConnect(odbc::odbc(), 
                      Driver = "SQL Server", 
                      Server = "localhost\\SQLEXPRESS", 
                      Database = "life_expectancy", 
                      Trusted_Connection = "True")
## Load tables from MongoDB
```
```{r, echo= FALSE}
conn <- mongo(collection = "countries", db = "marketing", url = "mongodb://localhost")
countries <- conn$find('{}') 
dim(countries)
countries$ymd <- as.Date(countries$ymd)
dbWriteTable(db1, "countries",countries ,overwrite=TRUE)
```

```{r,echo =FALSE}
conn1 <- mongo(collection = "countries_life_expectancy", db = "marketing", url = "mongodb://localhost")
countries_life_expectancy <- conn1$find('{}') 
dim(countries_life_expectancy)
countries_life_expectancy$ymd <- as.Date(countries_life_expectancy$ymd)
dbWriteTable(db1, "countries_life_expectancy",countries_life_expectancy ,overwrite=TRUE)
```


```{r, echo = FALSE}
conn2 <- mongo(collection = "income_groups", db = "marketing", url = "mongodb://localhost")
income_groups <- conn2$find('{}') 
dim(income_groups)
income_groups$ymd <- as.Date(income_groups$ymd)
dbWriteTable(db1, "income_groups",income_groups ,overwrite=TRUE)

```

```{r, echo =FALSE}
conn3 <- mongo(collection = "income_group_by_year", db = "marketing", url = "mongodb://localhost")
income_group_by_year <- conn3$find('{}') 
dim(income_group_by_year)
income_group_by_year$ymd <- as.Date(income_group_by_year$ymd)
dbWriteTable(db1, "income_group_by_year",income_group_by_year ,overwrite=TRUE)
```

```{r, echo =FALSE}
conn4 <- mongo(collection = "countries_by_change_in_life_expectancy", db = "marketing", url = "mongodb://localhost")
countries_by_change_in_life_expectancy <- conn4$find('{}') 
dim(countries_by_change_in_life_expectancy)
dbWriteTable(db1, "countries_by_change_in_life_expectancy",countries_by_change_in_life_expectancy,overwrite=TRUE)
```